= Pflichtenheft
:project_name: Projektname
== __{project_name}__

[options="header"]
[cols="1, 1, 1, 1, 4"]
|===
|Version | Status      | Bearbeitungsdatum   | Autoren(en) |  Vermerk
|0.1     | In Arbeit   | 10.10.2017          | Autor       | Initiale Version
|===

== Zweck dieses Dokuments
Dieses Dokument stellt die Software Requirements Specification (SRS, deutsch: in der Nähe eines Pflichtenheftes) des Projekts Videoshop dar. Es soll einen Überblick über das zu erstellende Softwareprodukt geben und dient als Grundlage für die Kommunikation zwischen den Interessengruppen des Projekts, insbesondere dem Kunden und dem Entwicklungsteam. Es ist erwünscht, dieses Dokument als Grundlage für einen Vertrag zwischen dem Kunden und dem Softwareentwickler zu haben, und sollte daher validiert und auf Konsistenz überprüft werden. Der Pflichtenheft beschreibt, was das gewünschte System zu tun hat und teilweise, wie der Softwareentwickler die Lösung umsetzen will.

Im Allgemeinen sollte der Pflichtenheft korrekt, vollständig und konsistent sein. Da es am Ende des Projekts verwendet wird, um zu überprüfen, ob die definierte Software bereitgestellt wurde oder nicht, sollte dieses Ziel überprüfbar sein. Es wird während des gesamten Projekts verwendet und konsultiert, deshalb sollte der Inhalt nachvollziehbar sein. In Verbindung mit dem oben Gesagten ist es wünschenswert, dass es einfach zu ändern ist, auch wenn Änderungen auf ein Minimum beschränkt werden sollten, nachdem sich die Beteiligten einmal über den Inhalt geeinigt haben. Da sich jedoch die Anforderungen und Umstände während eines Projekts ständig ändern, sind Anpassungen zu erwarten und zu dokumentieren.


== Inhaltsverzeichnis
Dieses Dokument benötigt ein Inhaltsverzeichnis. Es existieren mehrere Einbindungsmöglichkeiten.

== Zusammenfassung
Eine kurze Beschreibung des Dokuments. Wenige Absätze.

== Aufgabenstellung und Zielsetzung
Die Besitzerin eines kleinen Blumenladens braucht eine Software, die ihren Alltag und die Interaktionen mit Kunden
und mit dem Großhändler erleichtert und automatisiert. Sowohl Kunden als auch der Großhändler können
über eine Webapplikation Bestellungen aufgeben bzw. bestätigen, wobei auch immer der aktuelle Warenbestand angezeigt wird.
Außerdem hat die Besitzerin die Möglichkeit, detailierte Rechnungen schnell und einfach direkt nach der Beratung an die
Laufkundschaft auszustellen.

Einzelkunden können online aus dem Katalog Waren wie beispielsweise Schnittblumen, Topfblumen, Sträusse und Zubehör
bestellen. Jeder Kunde muss, um eine Bestellung aufgeben zu können, ein Kundenkonto anlegen. Großkunden wie Firmen können
zusätzlich zur Bestellung einen Pflanzenservice beantragen, welcher die wöchentliche Pflege der bestellten Pflanzen sowie
die Versorgung mit frischen Schnittblumen beinhalten kann. Für die zeitliche Planung bietet die Applikation daher einen
Kalender in den wichtige Termine und Informationen automatisch eingetragen werden.

Um immer genügend Waren auf Vorrat zu haben und damit keine Engpässe entstehen, kann die Ladeninhaberin jederzeit
den Bestand des Großhändlers abfragen und neue Waren bestellen. Dabei wird die Rechnung des Großhändlers als Ausgabe
in die Abrechnung aufgenommen. Für den Fall dass der Großhändler ein neues Produkt anbietet, hat die Floristin die
Möglichkeit, dieses Produkt auch in ihr Angebot aufzunehmen.

Sollte ein Kunde einen speziellen Wunsch wie zum Beispiel die Ausschmückung eines Events haben, kann die Besitzerin
bei einem Beratungsgespräch alle Details mit der Software aufnehmen und eine angepasste Rechnung erstellen.

Die wesentliche Erleichterung die die Software bietet ist, dass bei jedem Verkauf bzw. Auftrag alle Änderungen wie der
Kassen- und Warenstand von der Software aktualisiert werden, die Verkäuferin muss diese nicht manuell verändern. Zudem
wird eine jederzeit aktuelle Übersicht dieser Stände geboten, damit eine effektive Geschäftsführung möglich ist.

== Produktnutzung
Dieser Abschnitt gibt eine Übersicht darüber, wie und unter welchen Umständen das Produkt später genutzt werden soll.
Die Software soll zum Vertrieb von Produkten und Dienstleistungen genutzt werden, und dabei den Verwaltungsaufwand für Inhaberin und Mitarbeiter soweit wie möglich minimieren.
Das System soll für folgende Browser zugänglich und visuell optimiert sein:

- Firefox 60+
- Chrome 66+
- Safari 11.1+

Die zukünftigen, primären Nutzer der Software sind Inhaberin und Mitarbeiter des Blumensladen sowie deren Kunden. Es ist anzunehmen, dass alle Nutzergruppen rudimentäre Erfahrungen mit typischen webbasierten Navigationsschemata beitzen.
Der spätere Pflegeaufwand der Software soll sich nach Möglichkeit in Grenzen halten, da die Kundin weder über die dafür notwendige Zeit noch über die erforderlichen technischen Fähigkeiten verfügt.

== Interessensgruppen (Stakeholders)


Dies ist die Übersicht über alle realen und juristischen Personen, welche Einfluss auf das Projekt haben.
In der unten stehenden Tabelle, werden diese Interessensgruppen aufgelistet. Dabei werden ihre wichtigsten Ziele in Hinblick auf das Projekt beschrieben und ihre Bedeutung durch Zahlen Zwischen 1(geringe Bedeutung) und 5(hohe Bedeutung) aufgelistet.

[options="header", cols="2, ^1, 4, 4"]
|===
|Name
|Priority (1..5)
|Beschreibung
|Ziele

|Die Inhaberin (Frau Floris)
|5
|Die Inhaberin des Blumenladens und Auftragsgeberin.
a|
- Die Software soll Arbeitsabläufe unterstützen, Vereinfachen und Übersichtlicher gestalten.

- Erweiterung ihres Angebots für größere Kunden

- Unterstützung bei großen Aufträgen

|Angestellte/r
|3
|Mitarbeiter im Blumenladen.
a|
- Leichte Bedingung der Software im Arbeitsalltag

|Kunde (Privat)
|4
|Registrierter Kunde der Blumen kaufen möchte.
a|
- Einfaches kaufen von einzelnen oder mehreren Blumen

- Einsicht über die angebotenen Produkte

|Kunde (Firma)
|4
|Eine Firma die Blumen kaufen möchte.
a|
- Buchung von verschiedenen Services zu entsprechenden Bestellungen

|Großhändler
|4
|Ein Großhändler für Blumen der Frau Floris beliefert.
a|
- Einsehen von Bestellungen und deren Termin

|Entwickler
|3
|Die Gruppe an Entwicklern die für die konkrete Umsetzung und Implementierung zuständig ist.
a|
- Leichte Bedienbarkeit für Inhaberin und Kunden
- Einfache Instandhaltung und Pflege

|===

== Systemgrenze und Top-Level-Architektur

=== Kontextdiagramm
Das Kontextdiagramm zeigt das geplante Software-System in seiner Umgebung. Zur Umgebung gehören alle Nutzergruppen des Systems und Nachbarsysteme. Die Grafik kann auch informell gehalten sein. Überlegen Sie sich dann geeignete Symbole. Die Grafik kann beispielsweise mit Visio erstellt werden. Wenn nötig, erläutern Sie diese Grafik.

=== Top-Level-Architektur
Dokumentieren Sie ihre Top-Level-Architektur mit Hilfe eines Komponentendiagramm.

== Anwendungsfälle

=== Akteure

Akteure sind die Benutzer des Software-Systems oder Nachbarsysteme, welche darauf zugreifen. Dokumentieren Sie die Akteure in einer Tabelle. Diese Tabelle gibt einen Überblick über die Akteure und beschreibt sie kurz. Die Tabelle hat also mindestens zwei Spalten (Akteur Name und Kommentar).
Weitere relevante Spalten können bei Bedarf ergänzt werden.

// See http://asciidoctor.org/docs/user-manual/#tables
[options="header"]
[cols="1,4"]
|===
|Name |Beschreibung
|...  |...
|===

=== Überblick Anwendungsfalldiagramm
Anwendungsfall-Diagramm, das alle Anwendungsfälle und alle Akteure darstellt

=== Anwendungsfallbeschreibungen
Dieser Unterabschnitt beschreibt die Anwendungsfälle. In dieser Beschreibung müssen noch nicht alle Sonderfälle und Varianten berücksichtigt werden. Schwerpunkt ist es, die wichtigsten Anwendungsfälle des Systems zu finden. Wichtig sind solche Anwendungsfälle, die für den Auftraggeber, den Nutzer den größten Nutzen bringen.
Für komplexere Anwendungsfälle ein UML-Sequenzdiagramm ergänzen.
Einfache Anwendungsfälle mit einem Absatz beschreiben.
Die typischen Anwendungsfälle (Anlegen, Ändern, Löschen) können zu einem einzigen zusammengefasst werden.

== Funktionale Anforderungen

=== Muss-Kriterien
Was das zu erstellende Programm auf alle Fälle leisten muss.

=== Kann-Kriterien
Anforderungen die das Programm leisten können soll, aber für den korrekten Betrieb entbehrlich sind.

== Nicht-Funktionale Anforderungen

=== Qualitätsziele

Dokumentieren Sie in einer Tabelle die Qualitätsziele, welche das System erreichen soll, sowie deren Priorität.

=== Konkrete Nicht-Funktionale Anforderungen

Beschreiben Sie Nicht-Funktionale Anforderungen, welche dazu dienen, die zuvor definierten Qualitätsziele zu erreichen.
Achten Sie darauf, dass deren Erfüllung (mindestens theoretisch) messbar sein muss.

== GUI Prototyp

In diesem Kapitel soll ein Entwurf der Navigationsmöglichkeiten und Dialoge des Systems erstellt werden.
Idealerweise entsteht auch ein grafischer Prototyp, welcher dem Kunden zeigt, wie sein System visuell umgesetzt werden soll.
Konkrete Absprachen - beispielsweise ob der grafische Prototyp oder die Dialoglandkarte höhere Priorität hat - sind mit dem Kunden zu treffen.

=== Überblick: Dialoglandkarte
Erstellen Sie ein Übersichtsdiagramm, das das Zusammenspiel Ihrer Masken zur Laufzeit darstellt. Also mit welchen Aktionen zwischen den Masken navigiert wird.
//Die nachfolgende Abbildung zeigt eine an die Pinnwand gezeichnete Dialoglandkarte. Ihre Karte sollte zusätzlich die Buttons/Funktionen darstellen, mit deren Hilfe Sie zwischen den Masken navigieren.

=== Dialogbeschreibung
Für jeden Dialog:

1. Kurze textuelle Dialogbeschreibung eingefügt: Was soll der jeweilige Dialog? Was kann man damit tun? Überblick?
2. Maskenentwürfe (Screenshot, Mockup)
3. Maskenelemente (Ein/Ausgabefelder, Aktionen wie Buttons, Listen, …)
4. Evtl. Maskendetails, spezielle Widgets

== Datenmodell

=== Überblick: Klassendiagramm
UML-Analyseklassendiagramm

=== Klassen und Enumerationen
Dieser Abschnitt stellt eine Vereinigung von Glossar und der Beschreibung von Klassen/Enumerationen dar. Jede Klasse und Enumeration wird in Form eines Glossars textuell beschrieben. Zusätzlich werden eventuellen Konsistenz- und Formatierungsregeln aufgeführt.

// See http://asciidoctor.org/docs/user-manual/#tables
[options="header"]
|===
|Klasse/Enumeration |Beschreibung |
|…                  |…            |
|===

== Akzeptanztestfälle
Mithilfe von Akzeptanztests wird geprüft, ob die Software die funktionalen Erwartungen und Anforderungen im Gebrauch erfüllt. Diese sollen und können aus den Anwendungsfallbeschreibungen und den UML-Sequenzdiagrammen abgeleitet werden. D.h., pro (komplexen) Anwendungsfall gibt es typischerweise mindestens ein Sequenzdiagramm (welches ein Szenarium beschreibt). Für jedes Szenarium sollte es einen Akzeptanztestfall geben. Listen Sie alle Akzeptanztestfälle in tabellarischer Form auf.
Jeder Testfall soll mit einer ID versehen werde, um später zwischen den Dokumenten (z.B. im Test-Plan) referenzieren zu können.

== Glossar
Sämtliche Begriffe, die innerhalb des Projektes verwendet werden und deren gemeinsames Verständnis aller beteiligten Stakeholder essentiell ist, sollten hier aufgeführt werden.
Insbesondere Begriffe der zu implementierenden Domäne wurden bereits beschrieben, jedoch gibt es meist mehr Begriffe, die einer Beschreibung bedürfen. +
Beispiel: Was bedeutet "Kunde"? Ein Nutzer des Systems? Der Kunde des Projektes (Auftraggeber)?

== Offene Punkte
Offene Punkte werden entweder direkt in der Spezifikation notiert. Wenn das Pflichtenheft zum finalen Review vorgelegt wird, sollte es keine offenen Punkte mehr geben.
