= Pflichtenheft
:project_name: Projektname
== __{project_name}__

[options="header"]
[cols="1, 1, 1, 1, 4"]
|===
|Version | Status      | Bearbeitungsdatum   | Autoren(en) |  Vermerk
|0.1     | In Arbeit   | 10.10.2017          | Autor       | Initiale Version
|===

== Zweck dieses Dokuments
Dieses Dokument stellt die Software Requirements Specification (SRS, deutsch: in der Nähe eines Pflichtenheftes) des Projekts Videoshop dar. Es soll einen Überblick über das zu erstellende Softwareprodukt geben und dient als Grundlage für die Kommunikation zwischen den Interessengruppen des Projekts, insbesondere dem Kunden und dem Entwicklungsteam. Es ist erwünscht, dieses Dokument als Grundlage für einen Vertrag zwischen dem Kunden und dem Softwareentwickler zu haben, und sollte daher validiert und auf Konsistenz überprüft werden. Der Pflichtenheft beschreibt, was das gewünschte System zu tun hat und teilweise, wie der Softwareentwickler die Lösung umsetzen will.

Im Allgemeinen sollte der Pflichtenheft korrekt, vollständig und konsistent sein. Da es am Ende des Projekts verwendet wird, um zu überprüfen, ob die definierte Software bereitgestellt wurde oder nicht, sollte dieses Ziel überprüfbar sein. Es wird während des gesamten Projekts verwendet und konsultiert, deshalb sollte der Inhalt nachvollziehbar sein. In Verbindung mit dem oben Gesagten ist es wünschenswert, dass es einfach zu ändern ist, auch wenn Änderungen auf ein Minimum beschränkt werden sollten, nachdem sich die Beteiligten einmal über den Inhalt geeinigt haben. Da sich jedoch die Anforderungen und Umstände während eines Projekts ständig ändern, sind Anpassungen zu erwarten und zu dokumentieren.


== Inhaltsverzeichnis
Dieses Dokument benötigt ein Inhaltsverzeichnis. Es existieren mehrere Einbindungsmöglichkeiten.

== Zusammenfassung
Eine kurze Beschreibung des Dokuments. Wenige Absätze.

== Aufgabenstellung und Zielsetzung
Die Besitzerin eines kleinen Blumenladens braucht eine Software, die ihren Alltag und die Interaktionen mit Kunden
und mit dem Großhändler erleichtert und automatisiert. Sowohl Kunden als auch der Großhändler können
über eine Webapplikation Bestellungen aufgeben bzw. bestätigen, wobei auch immer der aktuelle Warenbestand angezeigt wird.
Außerdem hat die Besitzerin die Möglichkeit, detailierte Rechnungen schnell und einfach direkt nach der Beratung an die
Laufkundschaft auszustellen.

Einzelkunden können online aus dem Katalog Waren wie beispielsweise Schnittblumen, Topfblumen, Sträusse und Zubehör
bestellen. Jeder Kunde muss, um eine Bestellung aufgeben zu können, ein Kundenkonto anlegen. Großkunden wie Firmen können
zusätzlich zur Bestellung einen Pflanzenservice beantragen, welcher die wöchentliche Pflege der bestellten Pflanzen sowie
die Versorgung mit frischen Schnittblumen beinhalten kann. Für die zeitliche Planung bietet die Applikation daher einen
Kalender in den wichtige Termine und Informationen automatisch eingetragen werden.

Um immer genügend Waren auf Vorrat zu haben und damit keine Engpässe entstehen, kann die Ladeninhaberin jederzeit
den Bestand des Großhändlers abfragen und neue Waren bestellen. Dabei wird die Rechnung des Großhändlers als Ausgabe
in die Abrechnung aufgenommen. Für den Fall dass der Großhändler ein neues Produkt anbietet, hat die Floristin die
Möglichkeit, dieses Produkt auch in ihr Angebot aufzunehmen.

Sollte ein Kunde einen speziellen Wunsch wie zum Beispiel die Ausschmückung eines Events haben, kann die Besitzerin
bei einem Beratungsgespräch alle Details mit der Software aufnehmen und eine angepasste Rechnung erstellen.

Die wesentliche Erleichterung die die Software bietet ist, dass bei jedem Verkauf bzw. Auftrag alle Änderungen wie der
Kassen- und Warenstand von der Software aktualisiert werden, die Verkäuferin muss diese nicht manuell verändern. Zudem
wird eine jederzeit aktuelle Übersicht dieser Stände geboten, damit eine effektive Geschäftsführung möglich ist.

== Produktnutzung
Dieser Abschnitt gibt eine Übersicht darüber, wie und unter welchen Umständen das Produkt später genutzt werden soll.
Die Software soll zum Vertrieb von Produkten und Dienstleistungen genutzt werden, und dabei den Verwaltungsaufwand für Inhaberin und Mitarbeiter soweit wie möglich minimieren.
Das System soll für folgende Browser zugänglich und visuell optimiert sein:

- Firefox 60+
- Chrome 66+
- Safari 11.1+

Die zukünftigen, primären Nutzer der Software sind Inhaberin und Mitarbeiter des Blumensladen sowie deren Kunden. Es ist anzunehmen, dass alle Nutzergruppen rudimentäre Erfahrungen mit typischen webbasierten Navigationsschemata beitzen.
Der spätere Pflegeaufwand der Software soll sich nach Möglichkeit in Grenzen halten, da die Kundin weder über die dafür notwendige Zeit noch über die erforderlichen technischen Fähigkeiten verfügt.

== Interessensgruppen (Stakeholders)


Dies ist die Übersicht über alle realen und juristischen Personen, welche Einfluss auf das Projekt haben.
In der unten stehenden Tabelle, werden diese Interessensgruppen aufgelistet. Dabei werden ihre wichtigsten Ziele in Hinblick auf das Projekt beschrieben und ihre Bedeutung durch Zahlen Zwischen 1(geringe Bedeutung) und 5(hohe Bedeutung) aufgelistet.

[options="header", cols="2, ^1, 4, 4"]
|===
|Name
|Priority (1..5)
|Beschreibung
|Ziele

|Die Inhaberin (Frau Floris)
|5
|Die Inhaberin des Blumenladens und Auftragsgeberin.
a|
- Die Software soll Arbeitsabläufe unterstützen, Vereinfachen und Übersichtlicher gestalten.

- Erweiterung ihres Angebots für größere Kunden

- Unterstützung bei großen Aufträgen

|Angestellte/r
|3
|Mitarbeiter im Blumenladen.
a|
- Leichte Bedingung der Software im Arbeitsalltag

|Kunde (Privat)
|4
|Registrierter Kunde der Blumen kaufen möchte.
a|
- Einfaches kaufen von einzelnen oder mehreren Blumen

- Einsicht über die angebotenen Produkte

|Kunde (Firma)
|4
|Eine Firma die Blumen kaufen möchte.
a|
- Buchung von verschiedenen Services zu entsprechenden Bestellungen

|Großhändler
|4
|Ein Großhändler für Blumen der Frau Floris beliefert.
a|
- Einsehen von Bestellungen und deren Termin

|Entwickler
|3
|Die Gruppe an Entwicklern die für die konkrete Umsetzung und Implementierung zuständig ist.
a|
- Leichte Bedienbarkeit für Inhaberin und Kunden
- Einfache Instandhaltung und Pflege

|===

== Systemgrenze und Top-Level-Architektur

=== Kontextdiagramm
Das Kontextdiagramm zeigt das geplante Software-System in seiner Umgebung. Zur Umgebung gehören alle Nutzergruppen des Systems und Nachbarsysteme. Die Grafik kann auch informell gehalten sein. Überlegen Sie sich dann geeignete Symbole. Die Grafik kann beispielsweise mit Visio erstellt werden. Wenn nötig, erläutern Sie diese Grafik.

=== Top-Level-Architektur
Dokumentieren Sie ihre Top-Level-Architektur mit Hilfe eines Komponentendiagramm.

== Anwendungsfälle

=== Akteure

Akteure sind die Benutzer des Software-Systems oder Nachbarsysteme, welche darauf zugreifen. Dokumentieren Sie die Akteure in einer Tabelle. Diese Tabelle gibt einen Überblick über die Akteure und beschreibt sie kurz. Die Tabelle hat also mindestens zwei Spalten (Akteur Name und Kommentar).
Weitere relevante Spalten können bei Bedarf ergänzt werden.

// See http://asciidoctor.org/docs/user-manual/#tables
[options="header"]
[cols="1,4"]
|===
|Name |Beschreibung
|...  |...
|===

=== Überblick Anwendungsfalldiagramm
Anwendungsfall-Diagramm, das alle Anwendungsfälle und alle Akteure darstellt

=== Anwendungsfallbeschreibungen
Dieser Unterabschnitt beschreibt die Anwendungsfälle. In dieser Beschreibung müssen noch nicht alle Sonderfälle und Varianten berücksichtigt werden. Schwerpunkt ist es, die wichtigsten Anwendungsfälle des Systems zu finden. Wichtig sind solche Anwendungsfälle, die für den Auftraggeber, den Nutzer den größten Nutzen bringen.
Für komplexere Anwendungsfälle ein UML-Sequenzdiagramm ergänzen.
Einfache Anwendungsfälle mit einem Absatz beschreiben.
Die typischen Anwendungsfälle (Anlegen, Ändern, Löschen) können zu einem einzigen zusammengefasst werden.

== Funktionale Anforderungen

Dieser Abschnitt ist eine Übersicht aller Funktionalen Anforderungen. Die Tabellen enthalten:

- Eine einzigartige ID zur Referenz im Projekt
- Die Version der Anforderung, da sich diese im Laufe des Projekts ändern kann
- Kurzname der Anforderung
- Beschreibung der Anforderung

=== Muss-Kriterien
Folgende Funktionen müssen für den korrekten Betrieb existieren.

[options="header", cols="2h, 1, 3, 12"]
|===
|ID
|Version
|Name
|Description

|[[F0010]]<<F0010>>
|v0.1
|Authentifizierung
a|
Das System soll in öffentlich zugängliche Teile und Passwort geschützte Teile einteilbar sein. Ein registrierter
Benutzer soll die möglichkeit haben, sich anhand folgender Daten zu Authentifizieren:

- E-Mail Adresse / Nutzername
- Passwort


|[[F0020]]<<F0020>>
|v0.1
|Registrierung
a|
Unregistrierte Kunden sollen ein Kundenkonto anlegen können. Folgende Informationen sind dabei erforderlich:

- E-Mail Adresse
- Passwort

|[[F0030]]<<F0030>>
|v0.1
|Kundenart
a|
Es soll folgende Arten von Kunden geben:

- Privatkunden
- Firmenkunden

|[[F0031]]<<F0031>>
|v0.1
|Kundenart ändern
a|

Die Inhaberin soll die Möglichkeit haben, die Kundenart zu eines Kunden zu ändern.

|[[F0100]]<<F0100>>
|v0.1
|Bestand
a|
Der Warenbestand soll jederzeit aktuell sein und persistent gespeichert werden.

|[[F0101]]<<F0101>>
|v0.1
|Bestand ändern
a|
Die Menge eines Produktes im Warenbestand soll jederzeit änderbar sein.

|[[F0102]]<<F0102>>
|v0.1
|Produkt zum Bestand hinzufügen
a|
Die Inhaberin oder ein(e) Mitarbeiter(in) soll ein neues Produkt erstellen und zum Warenbestand hinzufügen können.
Folgende Daten sind erforderlich:

- Produktname
- Preis pro Stück
- Produktfarbe
- Lieferzeit

|[[F0103]]<<F0103>>
|v0.1
|Produkt vom Bestand entfernen
a|
Die Inhaberin oder ein(e) Mitarbeiter(in) soll jederzeit ein Produkt aus dem Bestand löschen können.

|[[F0104]]<<F0104>>
|v0.1
|Produktinformationen bearbeiten
a|
Die Inhaberin oder ein(e) Mitarbeiter(in) soll die Möglichkeit haben, alle relevanten Informationen zu einem Produkt
jederzeit ändern zu können.

|[[F0110]]<<F0110>>
|v0.1
|Katalog
a|
Der Warenbestand (<<F0100>>) soll durch einen schreibgeschützten Zugriff zugänglich sein.

|[[F0111]]<<F0111>>
|v0.1
|Katalog anzeigen
a|
Der Benutzer soll den Inhalt des Katalogs einsehen können.

|[[F0112]]<<F0112>>
|v0.1
|Katalog filtern
a|
Der Benutzer soll den angezeigten Inhalt des Katalogs nach folgenden Kriterien filtern können:

- Preis
- Farbe der Ware
- Art der Ware

|[[F0120]]<<F0120>>
|v0.1
|Produktdetails
a|
Der Benutzer soll zu jedem Produkt alle Produktdetails einsehen können, wie zum Beispiel:

- Kurze Information zur Art des Produkts
- Verfügbare Menge
- Preis
- Lieferdauer

|[[F0200]]<<F0200>>
|v0.1
|Warenkorb
a|
Jeder registrierte Benutzer soll einen eigenen Warenkorb haben, in dem er Produkte für den Erwerb zwischenspeichern kann.

|[[F0201]]<<F0201>>
|v0.1
|Produkt in den Warenkorb legen
a|
Der Benutzer soll eine beliebige Anzahl an beliebige Produkte aus dem Warenkatalog (<<F0110>>) in den Warenkorb
"legen" können. Dabei muss im Warenkorb des Benutzers ein Eintrag mit dem Produkt und der Anzahl des Produkts erstellt
und gespeichert werden.

Unregistrierte Benutzer müssen sich registrieren (<<F0030>>), um Waren zum Warenkorb hinzufügen zu können.

|[[F0210]]<<F0210>>
|v0.1
|Warenkorb einsehen
a|
Jeder registrierte Benutzer soll den Inhalt seines Warenkorbs einsehen können. Dabei müssen folgende Daten angezeigt werden:

- Produktname
- Gewählte Anzahl
- Preis der einzelnen Produkte (für die gewählte Anzahl)
- Gesamtpreis des Warenkorbs

|[[F0211]]<<F0211>>
|v0.1
|Services buchen
a|
Firmenkunden sollen im Warenkorb zusätzlich zu den gewählten Produkten folgende Services dazubuchen können:

- wöchentliche Pflege
- wöchentliche Versorgung mit frischen Schnittblumen

|[[F0212]]<<F0212>>
|v0.1
|Lieferdatum wählen
a|
Der Benutzer soll die möglichkeit haben, ein Lieferdatum zu wählen, welcher der Bestellung hinzugefügt wird.

|[[F0220]]<<F0220>>
|v0.1
|Warenkorb kaufen
a|
Jeder registrierte Benutzer soll den Inhalt seines Warenkorbs kaufen können. Dabei muss geprüft werden, ob der Warenbestand
der gewählten Produkte ausreichend ist (<<F0230>>).

Falls die Prüfung positiv ausfällt, wird eine Bestellung angelegt (<<F0241>>).

|[[F0230]]<<F0230>>
|v0.1
|Warenbestand prüfen
a|
Es soll möglich sein zu prüfen, ob der Bestand eines Produkts einer gewünschten Mindestanzahl entspricht.

|[[F0240]]<<F0240>>
|v0.1
|Bestellung
a|
Die Software soll Bestellungen ermöglichen und speichern können.

|[[F0241]]<<F0241>>
|v0.1
|Bestellung anlegen
a|
Es soll möglich sein eine Bestellung mit den Produkten eines Warenkorbs zu erstellen.

Eine Bestellung soll mit dem Status "offen" initialisiert werden.

|[[F0242]]<<F0242>>
|v0.1
|Bestellung bezahlen
a|
Der Benutzer soll eine von ihm erstellte Bestellung bezahlen können.
Wenn dies erfolgt, soll der Status der Bestellung zu "bezahlt" geändert werden und der Kunde soll eine Rechnung
(<<F0500>>) mit allen relevanten Daten erhalten.

|[[F0243]]<<F0243>>
|v0.1
|Bestellung archivieren
a|
Eine Bestellung soll archiviert werden können.

Dies soll in der Regel passieren, wenn eine Bestellung vom Auftragnehmer
erfüllt worden ist und zum Status "abgeschlossen" übergeht.

|[[F0300]]<<F0300>>
|v0.1
|Kundenliste anzeigen
a|
Die Inhaberin oder ein(e) Mitarbeiter(in) soll die Möglichkeit haben, eine Liste mit allen
registrierten Benutzern einsehen zu können.

|[[F0310]]<<F0310>>
|v0.1
|Bestellungen einsehen
a|
Die Inhaberin oder ein(e) Mitarbeiter(in) soll die Möglichkeit haben, eine Liste mit allen Bestellungen einsehen zu können.
Diese Liste soll nach den drei verschiedenen Status (offen, bezahlt, abgeschlossen) gefiltert werden können.

|[[F0320]]<<F0320>>
|v0.1
|Bestellungen als bezahlt markieren
a|
Die Inhaberin oder ein(e) Mitarbeiter(in) soll die Möglichkeit haben, eine Bestellung im Falle einer Barzahlung als bezahlt
zu markieren.

|[[F0330]]<<F0330>>
|v0.1
|Bestellung beim Großhändler
a|
Das System soll eine Bestellung beim Großhändler in Form einer E-Mail machen können.

|[[F0331]]<<F0331>>
|v0.1
|Manuelle Bestellung beim Großhändler
a|
Die Inhaberin soll die Möglichkeit haben, manuell eine Bestellung beim Großhändler machen zu können.

|[[F0332]]<<F0332>>
|v0.1
|Bestellung beim Großhändler nach Termin
a|
Das System soll eine Bestellung beim Großhändler automatisch zu einem Bestimmten Termin machen können.

|[[F0400]]<<F0400>>
|v0.1
|Kasse
a|
Das System soll eine Kasse mit dem aktuellen Kassenstand führen.

|[[F0410]]<<F0410>>
|v0.1
|Kassenstand ändern
a|
Die Inhaberin oder ein(e) Mitarbeiter(in) soll jederzeit den Kassenstand ändern können.

|[[F0420]]<<F0420>>
|v0.1
|Kassenstand einsehen
a|
Die Inhaberin oder ein(e) Mitarbeiter(in) soll den Kassenstand einsehen können.

|[[F0500]]<<F0500>>
|v0.1
|Rechnung erstellen
a|
Das System soll die Möglichkeit haben, eine Rechnung mit folgenden Informationen zu erstellen:

- Rechnungsdatum
- Käuferdaten
- Erworbene Produkte / Services
- Preis der einzelnen Produkte / Services
- Anderweitige Kosten
- Gesamtpreis
- Verkäufername

Alle Rechnungen sollen persistent gespeichert werden.

|[[F0510]]<<F0510>>
|v0.1
|Rechnungen einsehen
a|
Die Inhaberin soll eine Liste mit allen Rechnungen einsehen können. Folgende Daten sollen in der Liste angezeigt werden:

- Rechnungsdatum
- Käufername
- Gesamtpreis
- Hyperlink zur Rechnung

|===

=== Kann-Kriterien
Anforderungen die das Programm leisten können soll, aber für den korrekten Betrieb entbehrlich sind.

[options="header", cols="2h, 1, 3, 12"]
|===
|ID
|Version
|Name
|Description

|[[F0600]]<<F0600>>
|v0.1
|Produktbilder ändern / hinzufügen
a|
Möglichkeit, Bilder hochzuladen und zu Produkten hinzuzufügen bzw. zu löschen. Mindestanforderungen:

- PNG- / JPG-Format
- Format: 1:1

|[[F0700]]<<F0700>>
|v0.1
|Produktrabatt
a|
Möglichkeit, den Preis eines Produktes zu Reduzieren. Der Rabatt wird im Katalog und bei den Produktdetails angezeigt
und der Preis wird automatisch neu berechnet.

|[[F0710]]<<F0710>>
|v0.1
|neuen Produktrabatt erstellen
a|
Möglichkeit, zu einem Produkt einen neuen Rabatt zu erstellen. Erreichbar durch die Detailansicht eines Produktes.

|[[F0800]]<<F0800>>
|v0.1
|Produktkommentar
a|
Möglichkeit, dass ein Produkt ein, oder mehrere Produktkommentare besitzt. Ein Kommentar beinhaltet folgende Daten:

- E-Mail Adresse / Nutzername des Autors
- Erstellungsdatum
- Kommentartext

|[[F0810]]<<F0810>>
|v0.1
|Produktkommentar erstellen
a|
Jeder registrierte Benutzer hat die Möglichkeit einen neuen Kommentar zu erstellen. Die Maximallänge eines
Kommentartextes beträgt 500 Zeichen.

|[[F0820]]<<F0820>>
|v0.1
|Produktkommentar löschen
a|
Ein registrierter Benutzer kann selbst erstellte Kommentare jederzeit wieder löschen.

Die Inhaberin kann jeden Kommentar löschen.

|===

== Nicht-Funktionale Anforderungen

=== Qualitätsziele

Dokumentieren Sie in einer Tabelle die Qualitätsziele, welche das System erreichen soll, sowie deren Priorität.

=== Konkrete Nicht-Funktionale Anforderungen

Beschreiben Sie Nicht-Funktionale Anforderungen, welche dazu dienen, die zuvor definierten Qualitätsziele zu erreichen.
Achten Sie darauf, dass deren Erfüllung (mindestens theoretisch) messbar sein muss.

== GUI Prototyp

In diesem Kapitel soll ein Entwurf der Navigationsmöglichkeiten und Dialoge des Systems erstellt werden.
Idealerweise entsteht auch ein grafischer Prototyp, welcher dem Kunden zeigt, wie sein System visuell umgesetzt werden soll.
Konkrete Absprachen - beispielsweise ob der grafische Prototyp oder die Dialoglandkarte höhere Priorität hat - sind mit dem Kunden zu treffen.

=== Überblick: Dialoglandkarte
Erstellen Sie ein Übersichtsdiagramm, das das Zusammenspiel Ihrer Masken zur Laufzeit darstellt. Also mit welchen Aktionen zwischen den Masken navigiert wird.
//Die nachfolgende Abbildung zeigt eine an die Pinnwand gezeichnete Dialoglandkarte. Ihre Karte sollte zusätzlich die Buttons/Funktionen darstellen, mit deren Hilfe Sie zwischen den Masken navigieren.

=== Dialogbeschreibung
Für jeden Dialog:

1. Kurze textuelle Dialogbeschreibung eingefügt: Was soll der jeweilige Dialog? Was kann man damit tun? Überblick?
2. Maskenentwürfe (Screenshot, Mockup)
3. Maskenelemente (Ein/Ausgabefelder, Aktionen wie Buttons, Listen, …)
4. Evtl. Maskendetails, spezielle Widgets

== Datenmodell

=== Überblick: Klassendiagramm
UML-Analyseklassendiagramm

=== Klassen und Enumerationen
Dieser Abschnitt stellt eine Vereinigung von Glossar und der Beschreibung von Klassen/Enumerationen dar. Jede Klasse und Enumeration wird in Form eines Glossars textuell beschrieben. Zusätzlich werden eventuellen Konsistenz- und Formatierungsregeln aufgeführt.

// See http://asciidoctor.org/docs/user-manual/#tables
[options="header"]
|===
|Klasse/Enumeration |Beschreibung |
|…                  |…            |
|===

== Akzeptanztestfälle
Mithilfe von Akzeptanztests wird geprüft, ob die Software die funktionalen Erwartungen und Anforderungen im Gebrauch erfüllt. Diese sollen und können aus den Anwendungsfallbeschreibungen und den UML-Sequenzdiagrammen abgeleitet werden. D.h., pro (komplexen) Anwendungsfall gibt es typischerweise mindestens ein Sequenzdiagramm (welches ein Szenarium beschreibt). Für jedes Szenarium sollte es einen Akzeptanztestfall geben. Listen Sie alle Akzeptanztestfälle in tabellarischer Form auf.
Jeder Testfall soll mit einer ID versehen werde, um später zwischen den Dokumenten (z.B. im Test-Plan) referenzieren zu können.

== Glossar
Sämtliche Begriffe, die innerhalb des Projektes verwendet werden und deren gemeinsames Verständnis aller beteiligten Stakeholder essentiell ist, sollten hier aufgeführt werden.
Insbesondere Begriffe der zu implementierenden Domäne wurden bereits beschrieben, jedoch gibt es meist mehr Begriffe, die einer Beschreibung bedürfen. +
Beispiel: Was bedeutet "Kunde"? Ein Nutzer des Systems? Der Kunde des Projektes (Auftraggeber)?

== Offene Punkte
Offene Punkte werden entweder direkt in der Spezifikation notiert. Wenn das Pflichtenheft zum finalen Review vorgelegt wird, sollte es keine offenen Punkte mehr geben.
