= Flower Power

== About

The flowershop module is a template project to bootstrap the Java project in the Software Engineering lab.
The project is supposed to be copied into the group's repository to get it started easily.
It contains the following features:

* a skeleton Java 8 web application based on Spring Boot and Salespoint framework (see `src/main/java`)
* a placeholder Asciidoc file in `src/main/asciidoc` for documentation

== How to run the application?

We use the package manager `yarn` to handle our dependencies. These dependencies are later getting bundled
together using `webpack`.

https://yarnpkg.com/lang/en/docs/install/[How to install yarn?]

* Run `yarn install` from inside the `src/main/app` directory to install the dependencies.
* Run `yarn run dev` to generate the bundles which you can then find inside `src/main/resources/static/resources`.
* In the IDE: find `Application.java`, right-click project, select "Run As > Java Application"
* From the command line: run `mvn spring-boot:run`

(If you only want to just take a look at the application you can spare yourself the hassle of using `yarn` by packaging the
application as shown below.)

== How to package the application?

* Run `mvn clean package`. The packaged application (a JAR in `target/`) can be run with `java -jar $jarName`.

== Dummy User Accounts

|===
|Username |Password

|admin |pass
|johndoe |pass
|larrybird |pass

|===